// Import necessary module from Redux Toolkit
import { createSlice } from '@reduxjs/toolkit';

// Define the type for the authentication state
export type AuthState = {
	loggedIn?: boolean; // A boolean flag indicating whether the user is logged in
};

// Initial state for the authentication slice
const initialState: AuthState = {};

// Create an authentication slice using Redux Toolkit
const authSlice = createSlice({
	name: 'auth', // Name of the slice
	initialState, // Initial state for the slice
	reducers: {
		// Reducer function to handle user login
		login(state) {
			state.loggedIn = true; // Set the 'loggedIn' flag to true
		},
		// Reducer function to handle user logout
		logout(state) {
			state.loggedIn = false; // Set the 'loggedIn' flag to false
		},
	},
});

// Extract the reducer function from the authSlice
const authReducer = authSlice.reducer;

// Export the login and logout actions generated by authSlice
export const { login, logout } = authSlice.actions;

// Export the authReducer as the default export for this module
export default authReducer;
