// Import necessary module from Redux Toolkit
import { createSlice } from '@reduxjs/toolkit';

// Define the possible themes as 'dark', 'light', or 'auto'
export type Theme = 'dark' | 'light' | 'auto';

export type SettingsState = {
	theme: Theme; // Theme setting to determine the app's appearance
};

export const themes: Theme[] = ['auto', 'dark', 'light'];

const initialState: SettingsState = {
	theme: themes[0], // Default theme is 'auto'
};

const settingsSlice = createSlice({
	name: 'settings',
	initialState,
	reducers: {
		setTheme(state, { payload }: { payload: Theme }) {
			state.theme = payload; // Update the theme based on the provided payload
		},
	},
});

const settingsReducer = settingsSlice.reducer;

// Export the setTheme action generated by settingsSlice
export const { setTheme } = settingsSlice.actions;

// Export the settingsReducer as the default export for this module
export default settingsReducer;
